# Audio
- name: Audio Engineering
  abbreviation:
  category: training
  sub-category: audio
  url: /audio/
  status: "Stable"
  modified: "2016-02-02"
  description: "A modular handbook containing best practices and recommended equipment for audio recording. It enables audio recordists and engineers to cost-effectively create the highest possible quality recordings."

