# Audio
- name: Audio Engineering
  abbreviation:
  category: training
  sub-category: audio
  url: /audio/
  icon:
  what: "A modular handbook containing best practices and recommended equipment for audio recording."
  why: "enables audio recordists and engineers to cost-effectively create the highest possible quality recordings."

